bq = [
    "How many milligrams are in a gram?",
    "What's the square root of 47 rounded to the nearest whole number?",
    "What type of number has more than two factors?",
    "What is another name for a whole number?",
    "What type of angle measures less than 90 degrees?",
    "What is the result of an addition process called?",
    "What acronym is used to remember the order of operations?",
    "What is the most commonly appearing number in a data set?",
    "Red, yellow, and blue are what kind of colours?",
    "Which famous artist painted the Mona Lisa?",
    "In a 4/4 time signature, how many quarter notes make up a bar?",
    "What type of instrument is a violin?",
    "If an action word is a verb, what describes a noun?",
    "What is the most common plural of 'fungus'?",
    "What type of word sounds like what it describes?",
    "What type of word is spelled the same backwards?",
    "Who was the first prime minister of Canada?",
    "In terms of date and time, what does BC stand for?",
    "Which civil rights activist famously 'had a dream'?",
    "Who was the first person to land on the moon?",
    "Butter, ON, and DNA are songs by which K-pop idol group?",
    "What does the acronym 'NGL' stand for?",
    "Son Goku is the protagonist of which popular anime?",
    "Which superhero was born on the fictional planet Krypton?",
    "FITB: 'Erm, what the -----?'",
    'What was the former name of the social networking service, X?',
    "What is the Mario Kart course where players race on a rainbow?",
    "What is the name of Minecraft's protagonist?",
    "What must Pac-Man avoid while eating all of the dots?",
    "Neon, Sage, and Fade are characters from which shooting game?",
    "What is the name of the Pokémon mascot?",
    "In Candy Crush, what does the announcer say upon level completion?",
    "What is the capital of China?",
    "Which continent has the most land area?",
    "What is the largest ocean on Earth?",
    "Berlin is the capital of what country?",
    "The Great Lakes are: Superior, Ontario, Erie, Huron, and what?",
    "FITB: The Great Pyramid of Giza is one of the Seven --- of the World.",
    "What is the chemical formula for water?",
    "What is the innermost part of bones called?",
    "What planet is furthest from the Sun?",
    "Which muscle is primarily used to perform a squat?",
    "What protective layer of air absorbs the Sun's UV radiation?",
    "What unit is used to measure force?",
    "What is a substance made up of only one type of atom?",
    "Which subatomic particle is negatively charged?",
    "Which organelle is known as the 'powerhouse of the cell?'",
    "At what temperature does water freeze?",
    "What type of energy does an object in motion have?",
    "Which famous physicist is credited with discovering gravity?",
    "Setter, libero, and outside hitter are positions in what sport?",
    "How many players stand on a basketball court at a time?",
    "In tennis, what word is used to represent a score of zero?",
    "What international soccer tournament is held every four years?",
    "In baseball, which player behind the batter catches the ball?",
    "'Nous faison' translates to what in English?",
    "'Ils sont droles' translates to what in English?",
    "Who, from the Bible, gained incredible strength from their hair?",
    "What is the name of the first book of the Bible?",
    "What was God's sign that he would never destroy the earth again?",
    "What was the name of the body of water that Moses parted?",
    "What was the name of Jesus' mother?",
    "Who is currently the youngest Youth Shepherd?",
    "What is the name of the leader of The Seed's service team?",
    "Which is the first class of the Life Series?",
    "Which house church role jots down prayer requests?",
    "Colgate, Crest, and Sensodyne are companies that make what product?",
    "What is the main ingredient in guacamole?",
    "What do bees collect to make honey?",
    "How many cards are in a deck?",
    "It is dangerous to eat raw chicken due to what bacteria?",
    "In 'Inside Out', what pizza topping does Riley express disgust towards?",
    "What type of joke prompts the listener to answer the door?",
    "Which hormone is commonly referred to as the 'happy hormone'?",
    "What part of your body is said to rumble when you're hungry?",
    "Which Canadian university commonly has its name abbreviated as 'UofT'?",
    "In the kids show, Dora the Explorer, what animal is the character, 'Boots'?",
    "What do the pastors of The Seed start their sermons with?",
    "What time does The Seed's service start?",
    "In billiards, what colour is the eight ball?",
    "Aries, Gemini, and Scorpio are examples of what type of sign?",
    "FITB: A multicultural and ----- worshipping congregation.",
    ]